### ISSUE TITLE
Project "Preview" failure: "Failed to prepare" error

### ISSUE THREAD

**Issue by livingstonel** [ssc-sp/DMPWCanada-APGDCanada#6]
From "projects" > open project DMP > top menu bar select "preview"

Error: Failed to prepare template
Exception: MaxRetryError
Message: HTTPConnectionPool(host='minio', port=9000): Max retries exceeded with url: /engine-wizard/templates/dsw%3Aquestionnaire-report%3A2.4.0/2d9b7904-abd8-4ff5-9270-ebc5b7c79ff5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec7552c040>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Confirmation that "Settings" for project are set to default document template "Questionnaire Report (Recommended)", document format set to "PDF Document" and saved. 

Attempted preview action twice between two different projects. Same failure error. 

Sample project link: http://federaldatasteward.scienceprogram.cloud:8080/projects/12702783-2647-4207-b933-e29b6bdcf669

![FailurePrepareTemplate-PreviewDMP](https://user-images.githubusercontent.com/68394502/157535530-773767e7-368c-4dd7-9fcb-5da9cd3305eb.PNG)

**Comment by low-decarie** [comment]
Updated and relaunched.  Functionality resolved.  Prod deployment will be more stable.
