### ISSUE TITLE
Project "New Document" Error - Unknown failure

### ISSUE THREAD

**Issue by livingstonel** [ssc-sp/DMPWCanada-APGDCanada#8]
![Document-Error](https://user-images.githubusercontent.com/68394502/159564172-234f1c4a-8ce4-4dce-9dce-7385b4bc6d67.PNG)

Tried to create a new document from a project using any of the formats available (ie. json, pdf, docx, etc) and it failed every time. We receive an "in progress" message in blue and eventually it appears to time out and change to error in red. No actually error message or explanation is received to help identify the problem further.

**Comment by low-decarie** [comment]
Updated and relaunched. Functionality resolved. Prod deployment will be more stable.
